<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Hyva\Theme\ViewModel\ProductCompare;
use Hyva\Theme\ViewModel\ProductListItem;
use Hyva\Theme\ViewModel\ProductPage;
use Hyva\Theme\ViewModel\Wishlist;
use Magento\Catalog\Block\Product\AbstractProduct;
use Magento\Catalog\Helper\Output as CatalogOutputHelper;
use Magento\Catalog\ViewModel\Product\OptionsData as ProductOptionsData;
use Magento\Framework\Escaper;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper
// phpcs:disable Generic.Files.LineLength.TooLong

/** @var AbstractProduct $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var ProductPage $productViewModel */
$productViewModel = $viewModels->require(ProductPage::class);

/** @var ProductListItem $productListItemViewModel */
$productListItemViewModel = $viewModels->require(ProductListItem::class);

/** @var CatalogOutputHelper $catalogOutputHelper */
$catalogOutputHelper = $this->helper(CatalogOutputHelper::class);

/** @var ProductCompare $compareViewModel */
$compareViewModel = $viewModels->require(ProductCompare::class);
/** @var Wishlist $wishlistViewModel */
$wishlistViewModel = $viewModels->require(Wishlist::class);

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

$productOptionsViewmodel = $viewModels->require(ProductOptionsData::class);

/** @var Magento\Catalog\Model\Product $product */
$product = $block->getData('product');
$imageDisplayArea = $block->getData('image_display_area');
$templateType = $block->getData('template_type');
$viewMode = $block->getData('view_mode');
$showDescription = $block->getData('show_description');
$showAddToWishlist = $wishlistViewModel->isEnabled();
$showAddToCompare = $compareViewModel->showInProductList();
$viewIsGrid = $viewMode === 'grid';

if (!$product) {
    return '';
}
$productId = $product->getId();
$options   = $productOptionsViewmodel->getOptionsData($product);
$uniqueId = '_' . uniqid();

$hideDetails       = $block->getData('hide_details') ?: false;
$hideRatingSummary = $block->getData('hide_rating_summary') ?: false;

$imageCustomAttributes = $product->getData('image_custom_attributes')
    ?? $block->getData('image_custom_attributes')
    ?? [];
/** @var Hyva\Theme\ViewModel\HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(\Hyva\Theme\ViewModel\HeroiconsOutline::class);
?>

<?php if ($product->isSaleable()): ?>
<form method="post" class=" product_addtocart_form product product-item"
      action="<?= $escaper->escapeUrl($productViewModel->getAddToCartUrl($product, ['useUencPlaceholder' => true])) ?>"
    <?php if ($product->getOptions()): ?>
        enctype="multipart/form-data"
    <?php endif; ?>
>
    <div  class="item card flex flex-col w-full <?= $viewIsGrid ? '' : 'md:flex-row' ?>"  x-data="{cart_popup:false, item:1, Shop_btn:false, cart_icon:false}" @mouseover="Shop_btn = true" @mouseleave="Shop_btn = false" x-init="$watch('cart_popup', value => {
    document.body.classList.toggle('overflow-hidden', value);})" >
    <!-- Model -->
     <div x-show="cart_popup" x-cloak @mouseover="Shop_btn = false"
         class="fixed inset-0 flex items-center justify-center text-left bg-white bg-opacity-50 z-30">
        <div  @click.away="cart_popup = false" class="w-96 max-h-screen overflow-auto bg-white shadow-xl rounded-lg p-10 text-gray-700 relative">
            <a href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>"
               class="block m-auto w-40 mb-3 <?= $viewIsGrid ? '' : 'md:w-2/6 md:mb-0 md:mr-5' ?>"
               tabindex="-1">
                <?= $block->getImage($product, $imageDisplayArea)
                    ->setTemplate('Magento_Catalog::product/list/image.phtml')
                    ->setData('custom_attributes', $imageCustomAttributes)
                    ->setProductId($productId)
                    ->toHtml(); ?>
            </a>
            <span class="absolute top-0 left-0 w-full"><?= $this->getLayout()->createBlock("Magento\Framework\View\Element\Messages")->setTemplate("Magemen_QuickShop::messages.phtml")->toHtml() ?></span>

            <span @click="cart_popup=false"><?= $heroicons->plusHtml('w-8 cursor-pointer h-8 absolute top-2.5 right-2.5 rotate-45') ?></span>
            <div class="mt-2 items-center justify-center text-primary font-semibold text-lg <?= $viewIsGrid ? '' : 'md:text-left' ?>">
                <a class="product-item-link"
                   href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>">
                    <?= /* @noEscape */ $catalogOutputHelper->productAttribute($product, $product->getName(), 'name') ?>
                </a>
            </div>
            <div class="mt-2 text-gray-900"
                 x-data="initPriceBox_<?= /** @noEscape */ $uniqueId ?>()"
                 @update-prices-<?= (int)$productId ?>.window="updatePrice($event.detail);"
            >
                <?= /* @noEscape */ $productListItemViewModel->getProductPriceHtml($product) ?>
            </div>
            <?php if ($product->isAvailable() && !$hideDetails): ?>
                <?= /** @noEscape */ $block->getProductDetailsHtml($product) ?>
            <?php endif; ?>
            <div class="block text-left flex items-center w-full justify-between mt-3 mb-4">
                <div class="flex border border-black rounded-full ">
                    <a @click="item--"  class="w-11 h-9 mr-1 flex" :class="item <= 1?'pointer-events-none':''">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 m-auto" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18 12H6" />
                        </svg>
                    </a>
                    <input id="cart-<?= $escaper->escapeHtmlAttr($product->getId()) ?>-qty"
                       name="qty"
                       value="<?= $escaper->escapeHtmlAttr($block->getQty()) ?>"
                       :value="item"
                       type="number"
                       size="4"
                       step="any"
                       min="1"
                       title="<?= $escaper->escapeHtmlAttr(__('Qty')) ?>"
                       class="qty form-input w-11 h-9 text-center p-0 mr-1 drop-shadow-none border-0"
                       required="required"/>
                    <a @click="item++" class=" w-11 h-9 mr-1 flex">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 m-auto" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
                        </svg>
                    </a>
                </div>
                <?php if ($showAddToWishlist): ?>
                    <button x-data="initWishlist()"
                            @click.prevent="addToWishlist(<?= (int)$productId ?>)"
                            aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Wish List')) ?>"
                            type="button"
                            class="rounded-full w-9 h-9 bg-gray-200 p-0 border-0 inline-flex shrink-0 items-center justify-center text-gray-500 hover:text-red-600 ml-2">
                        <?= /** @noEscape */ $heroiconsSolid->heartHtml("w-5 h-5", 25, 25) ?>
                    </button>
                <?php endif; ?>
            </div>

            <?php if ($product->isSaleable()): ?>
                <button class="w-full btn btn-primary justify-center text-sm product_submit"
                        aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                >
                    <?= /** @noEscape */ $heroicons->shoppingCartHtml("h-6 w-6 border-current inline", 25, 25) ?>
                    <span class="ml-2 inline <?= $viewIsGrid ? 'md:ml-0 md:hidden lg:ml-2 lg:inline' : '' ?>">
                    <?= $escaper->escapeHtml(__('Add to Cart')) ?>
                    </span>
                </button>
            <?php else: ?>
            <div class="w-auto justify-center <?= $viewIsGrid ? 'mr-auto' : 'mr-auto md:mr-0' ?>">
                <?= $block->getChildBlock('stockstatus')->setData('product', $product)->toHtml() ?>
            </div>
            <?php endif; ?>
        </div>
    </div>
    <!-- Model -->
        <?= /** @noEscape */ $block->getBlockHtml('formkey') ?>
        <input type="hidden" name="product" value="<?= (int)$productId ?>"/>
        <?php foreach ($options as $optionItem): ?>
            <input type="hidden"
                   name="<?= $escaper->escapeHtml($optionItem['name']) ?>"
                   value="<?= $escaper->escapeHtml($optionItem['value']) ?>">
        <?php endforeach; ?>
        <?php else: ?>
        <div class="item product product-item card flex flex-col w-full <?= $viewIsGrid ? '' : 'md:flex-row' ?>"   x-data="{Shop_btn:false}" @mouseover="Shop_btn = true" @mouseleave="Shop_btn = false">
            <?php endif; ?>
            <?php /* Product Image */ ?>
        <div class="relative">
        <a href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>"
           class="relative product photo product-item-photo block mx-auto mb-3 <?= $viewIsGrid ? '' : 'md:mb-0 md:mr-5' ?>"
           tabindex="-1"
        >
            <?= $block->getImage($product, $imageDisplayArea)
                ->setTemplate('Magento_Catalog::product/list/image.phtml')
                ->setData('custom_attributes', $imageCustomAttributes)
                ->setProductId($productId)
                ->toHtml(); ?>
        </a>
        <?php if ($product->isSaleable()): ?>
        <!-- Product Model  button  -->
        <button x-cloak  x-show="!cart_popup && Shop_btn"  @click="cart_popup = !cart_popup" type="button" @mouseover="cart_icon = true" @mouseleave="cart_icon = false" class="btn bg-white overflow-hidden rounded-full text-black absolute h-11 w-32 top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 p-0"
        x-transition:enter="transition ease-out duration-300"
        x-transition:enter-start="opacity-0 -translate-y-2/3"
        x-transition:enter-end="opacity-100 -translate-y-1/2"
        x-transition:leave="transition ease-in duration-300"
        x-transition:leave-start="opacity-100 -translate-y-1/2"
        x-transition:leave-end="opacity-0 -translate-y-2/3"
        >
            <div class="relative m-auto h-full w-full flex justify-center items-center">
                <span><?= $escaper->escapeHtml(__('Quick Shop')) ?></span>
                <span x-show="cart_icon" x-cloak class="absolute flex justify-center items-center top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 h-full w-full text-white bg-black"
                        x-transition:enter="transition ease-out duration-100"
                        x-transition:enter-start="opacity-0 -translate-y-1/3"
                        x-transition:enter-end="opacity-100 -translate-y-1/2"
                        x-transition:leave="transition ease-in duration-100"
                        x-transition:leave-start="opacity-100 -translate-y-1/2"
                        x-transition:leave-end="opacity-0 -translate-y-1/3"
                >
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="w-8 h-8 md:h-6 md:w-6" width="25" height="25">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z"></path>
                    </svg>
                </span>
            </div>
        </button>
        <!-- Product Model  button  -->
        <?php else: ?>
        <!-- Product Model  button  -->
        <button x-cloak  x-show="Shop_btn" type="button" class="btn bg-white z-10 hover:bg-white overflow-hidden rounded-full text-black absolute h-11 w-32 top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 p-0"
        x-transition:enter="transition ease-out duration-300"
        x-transition:enter-start="opacity-0 -translate-y-2/3"
        x-transition:enter-end="opacity-100 -translate-y-1/2"
        x-transition:leave="transition ease-in duration-300"
        x-transition:leave-start="opacity-100 -translate-y-1/2"
        x-transition:leave-end="opacity-0 -translate-y-2/3"
        >
            <a href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>" class="relative m-auto h-full w-full flex justify-center items-center">
                <span><?= $escaper->escapeHtml(__('Out of Stock')) ?></span>
            <a/>
        </button>
        <!-- Product Model  button  -->
        <?php endif; ?>
        </div>
            <div class="product-info flex flex-col grow">
                <?php $productNameStripped = $block->stripTags($product->getName(), null, true); ?>
                <div class="mt-2 mb-1 items-center justify-center text-primary font-semibold text-lg <?= $viewIsGrid ? '' : 'md:text-left' ?>">
                    <a class="product-item-link"
                       href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>">
                        <?= /* @noEscape */ $catalogOutputHelper->productAttribute($product, $product->getName(), 'name') ?>
                    </a>
                </div>

                <?php if (!$hideRatingSummary): ?>
                    <div class="py-1 <?= $viewIsGrid ? '' : 'md:mx-0 md:w-auto' ?>">
                        <?= $block->getReviewsSummaryHtml($product, 'short') ?>
                    </div>
                <?php endif; ?>

                <?php if ($showDescription): ?>
                    <div class="mt-2 mb-1 items-center justify-center text-primary <?= $viewIsGrid ? '' : 'md:text-left' ?>">
                        <?= /* @noEscape */ $productViewModel->getShortDescriptionForProduct($product) ?>
                    </div>
                <?php endif; ?>

                <script>
                    function initPriceBox_<?= /** @noEscape */ $uniqueId ?>()
                    {
                        return {
                            updatePrice(priceData) {
                                const regularPriceLabel = this.$root.querySelector('.normal-price .price-label');
                                const regularPriceElement = this.$root.querySelector('.normal-price [data-price-type=finalPrice].price-wrapper .price');
                                const basePriceElement = this.$root.querySelector('.normal-price [data-price-type=basePrice].price-wrapper .price');
                                if (priceData.finalPrice.amount < priceData.oldPrice.amount) {
                                    regularPriceLabel.classList.add('hidden');
                                } else {
                                    regularPriceLabel.classList.remove('hidden');
                                }
                                regularPriceElement.innerText = hyva.formatPrice(priceData.finalPrice.amount);
                                basePriceElement && (basePriceElement.innerText = hyva.formatPrice(priceData.basePrice.amount));
                            }
                        }
                    }
                </script>
                <div class="pt-1 text-gray-900"
                     x-data="initPriceBox_<?= /** @noEscape */ $uniqueId ?>()"
                     @update-prices-<?= (int)$productId ?>.window="updatePrice($event.detail);"
                >
                    <?= /* @noEscape */ $productListItemViewModel->getProductPriceHtml($product) ?>
                </div>

                <div class=" pt-3 flex flex-wrap items-center <?= !$viewIsGrid ? '' : 'mt-auto' ?>">
                    <?php if ($showAddToWishlist): ?>
                        <button x-data="initWishlist()"
                                @click.prevent="addToWishlist(<?= (int)$productId ?>)"
                                aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Wish List')) ?>"
                                type="button"
                                class="rounded-full w-9 h-9 bg-gray-200 p-0 border-0 inline-flex shrink-0 items-center justify-center text-gray-500 hover:text-red-600 ml-2">
                            <?= $heroiconsSolid->heartHtml("w-5 h-5", 25, 25) ?>
                        </button>
                    <?php endif; ?>
                    <?php if ($showAddToCompare): ?>
                        <button x-data="initCompareOnProductList()"
                                @click.prevent="addToCompare(<?= (int)$productId ?>)"
                                aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Compare')) ?>"
                                type="button"
                                class="rounded-full w-9 h-9 bg-gray-200 p-0 border-0 inline-flex shrink-0 items-center justify-center text-gray-500 hover:text-yellow-500 ml-2">
                            <?= $heroicons->scaleHtml("w-5 h-5", 25, 25) ?>
                        </button>
                    <?php endif; ?>
                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                        <?= $addToBlock->setProduct($product)->getChildHtml() ?>
                    <?php endif; ?>
                </div>
            </div>
            <?php if ($product->isSaleable()): ?>
        </div>
</form>
<?php else: ?>
    </div>
<?php endif; ?>
